# Generated by Django 4.2.18 on 2025-01-21 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('release_year', models.CharField(blank=True, max_length=4, null=True)),
                ('imdb_rating', models.FloatField(blank=True, null=True)),
                ('director', models.TextField(blank=True, null=True)),
                ('cast', models.TextField(blank=True, null=True)),
                ('plot_summary', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
